/*
 * Global JS functions.
 */

// Actions ----------------------------------------------------------------------------------------

/**
 * Clear all other radio buttons in the same column of the <table> element generated by JSF
 * h:dataTable when the given radio button is clicked.
 * @param radio The <input type="radio"> element which was clicked.
 */
function dataTableSelectOneRadio(radio) {
    var id = radio.name.substring(radio.name.lastIndexOf(':'));
    var elements = radio.form.elements;
    for (var i = 0; i < elements.length; i++) {
        if (elements[i].name.substring(elements[i].name.lastIndexOf(':')) == id) {
            elements[i].checked = false;
        }
    }
    radio.checked = true;
}

/**
 * Add onmouseover and onmouseout functions to the rows (the <tr> elements) of the <table> with id
 * 'dataTable'. The onmouseover function will set the bgColor property of the row to #ff0000 (red)
 * and the onmouseout function will set the bgColor property of the row to #ffffff (white).
 */
function addHoverToDatatableRows() {
    var trs = document.getElementById('dataTable').getElementsByTagName('tbody')[0].getElementsByTagName('tr');
    for (var i = 0; i < trs.length; i++) {
        trs[i].onmouseover = new Function("this.bgColor='#ff0000'");
        trs[i].onmouseout = new Function("this.bgColor='#ffffff'");
    }
}

/**
 * Add onclick function to the rows (the <tr> elements) of the <table> element with id 'dataTable'.
 * The onclick function will call another function highlightrow(this).
 */
function addOnclickToDatatableRows() {
    var trs = document.getElementById('dataTable').getElementsByTagName('tbody')[0].getElementsByTagName('tr');
    for (var i = 0; i < trs.length; i++) {
        trs[i].onclick = new Function("highlightRow(this)");
    }
}

/**
 * Highlight the given row. This will toggle the bgColor property of the <tr> element between
 * #ff0000 (red) and #ffffff (white).
 * @param tr The <tr> element to be highlighted.
 */
function highlightRow(tr) {
    tr.bgColor = (tr.bgColor != '#ff0000') ? '#ff0000' : '#ffffff';
}

/**
 * Set highlight on the elements of the given ids.
 * @param ids The ids of the elements to be highlighted, comma separated.
 */
function setHighlight(ids) {
    var idsArray = ids.split(",");
    for (var i = 0; i < idsArray.length; i++) {
        var element = document.getElementById(idsArray[i]);
        if (element) {
            element.className = 'highlightInput';
        }
    }
}

/**
 * Set focus on the element of the given id.
 * @param id The id of the element to set focus on.
 */
function setFocus(id) {
    var element = document.getElementById(id);
    if (element && element.focus) {
        element.focus();
    }
}
